baseURL       = "https://nws-antoineride.netlify.app"
languageCode  = "fr-FR"
title         = "Antoine RIDE | Landing Page"
theme         = "roxo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "ACCUEIL"
    url     = "https://home.antoine-ride.fr"
    weight  = 1
  [[menu.nav]]
    name    = "A PROPOS"
    url     = "https://home.antoine-ride.fr/about"
    weight  = 2
  [[menu.nav]]
    name    = "PORTFOLIO"
    url     = "https://home.antoine-ride.fr/portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "ME CONTACTER"
    url     = "https://home.antoine-ride.fr/contact"
    weight  = 4
  [[menu.nav]]
    name    = ""
    url     = ""
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/myykjpje"
  
  # Navbar Action Button
  [params.navAction]
    status  = false
    name    = ""
    url     = ""
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "STEP IT UP"
    tagline               = "Antoine RIDE"
    primary_button        = "See Our Works"
    primary_button_url    = "portfolio"
    secondary_button      = "MON PORTFOLIO"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "Mes travaux !"
    subtitle  = " Du design, du développement, du marketing.. que dire.."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "TRAVAILLONS ENSEMBLE !"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = " Mon Portfolio "
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contactez moi !"
      address = "15 rue du pressoir Jouy Sur Eure"
      phone   = "07.71.10.60.34"
      email   = "antoineride.pro@gmail.com"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Liens"
        [[params.footer.sitemap.link]]
          name = "About"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Portfolio"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Réseaux Sociaux"
        [[params.footer.social.link]]
          name = "Twitter"
          url  = "#"
        [[params.footer.social.link]]
          name = "Behance"
          url  = "#"
        [[params.footer.social.link]]
          name = "Linkedin"
          url  = "#"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Tu as besoin d'aide ?"
        description = "N'hésite pas à me contacter et reste attentif aux nouveautés !"